Ottawa:
    x: 231
    y: 451
North Atlantic Ocean:
    x: 349
    y: 659
New York:
    x: 63
    y: 523
Washington:
    x: 61
    y: 617
Irminger Sea:
    x: 509
    y: 417
Irish Sea:
    x: 641
    y: 587
Iceland:
    x: 693
    y: 361
Greenland Sea:
    x: 841
    y: 207
Bay of Biscay:
    x: 475
    y: 1153
Azores:
    x: 327
    y: 1281
Mid Atlantic Ocean:
    x: 189
    y: 1561
South Atlantic Ocean:
    x: 261
    y: 2037
Rio de Janeiro:
    x: 177
    y: 1803
Madeira Sea:
    x: 329
    y: 1639
Norwegian Sea:
    x: 1013
    y: 401
Dakar:
    x: 429
    y: 2059
Morocco:
    x: 499
    y: 1959
English Channel:
    x: 707
    y: 1029
Gibraltar:
    x: 535
    y: 1795
Algiers:
    x: 739
    y: 1935
Madrid:
    x: 587
    y: 1595
Western Mediterranean:
    x: 1013
    y: 1591
Barcelona:
    x: 695
    y: 1655
Lisbon:
    x: 497
    y: 1527
Leon:
    x: 683
    y: 1451
Tunisia:
    x: 1055
    y: 1835
Sardinia:
    x: 1157
    y: 1635
Sfax:
    x: 1175
    y: 1931
Tripoli:
    x: 1367
    y: 2017
Malta:
    x: 1277
    y: 1821
Tyrrhenian Sea:
    x: 1263
    y: 1613
Central Mediterranean:
    x: 1549
    y: 1871
Sicily:
    x: 1391
    y: 1729
Rome:
    x: 1333
    y: 1531
Taranto:
    x: 1459
    y: 1533
Milan:
    x: 1197
    y: 1385
Gascony:
    x: 839
    y: 1311
Marseille:
    x: 977
    y: 1383
Venice:
    x: 1277
    y: 1317
Adriatic Sea:
    x: 1523
    y: 1505
Cyrenaica:
    x: 1717
    y: 1985
Croatia:
    x: 1495
    y: 1341
Albania:
    x: 1629
    y: 1547
Eastern Mediterranean:
    x: 2039
    y: 1861
Aegean Sea:
    x: 1899
    y: 1707
Athens:
    x: 1729
    y: 1619
Crete:
    x: 1911
    y: 1821
Egypt:
    x: 2057
    y: 2013
Suez:
    x: 2215
    y: 1967
Sudan:
    x: 2315
    y: 2141
Jordan:
    x: 2577
    y: 1819
Red Sea:
    x: 2421
    y: 2087
Damascus:
    x: 2525
    y: 1675
Gulf of Aden:
    x: 2769
    y: 2165
Arabian Sea:
    x: 3129
    y: 1819
West Indian Ocean:
    x: 3067
    y: 2043
Persian Gulf:
    x: 2959
    y: 1761
East Indian Ocean:
    x: 3293
    y: 1933
Bombay:
    x: 3285
    y: 1793
Delhi:
    x: 3333
    y: 1647
Karachi:
    x: 3209
    y: 1597
Shiraz:
    x: 3031
    y: 1593
Kabul:
    x: 3141
    y: 1409
Abadan:
    x: 2851
    y: 1455
Iraq:
    x: 2763
    y: 1545
Tehran:
    x: 2989
    y: 1389
Tabriz:
    x: 2845
    y: 1299
Turkmenistan:
    x: 3137
    y: 1233
Southern Caspian Sea:
    x: 2959
    y: 1133
Baku:
    x: 2833
    y: 1155
Kars:
    x: 2599
    y: 1323
Georgia:
    x: 2713
    y: 1163
Northern Caspian Sea:
    x: 2899
    y: 985
Kazakhstan:
    x: 3019
    y: 843
Grozny:
    x: 2711
    y: 987
Kuban:
    x: 2517
    y: 1043
Eastern Black Sea:
    x: 2485
    y: 1237
Sinope:
    x: 2401
    y: 1441
Adana:
    x: 2429
    y: 1569
Ankara:
    x: 2181
    y: 1479
Izmir:
    x: 2081
    y: 1607
Istanbul:
    x: 2005
    y: 1515
Western Black Sea:
    x: 2099
    y: 1355
Sevastopol:
    x: 2245
    y: 1131
Sea of Azov:
    x: 2335
    y: 1055
Kharkov:
    x: 2311
    y: 935
Odessa:
    x: 2119
    y: 1061
Kiev:
    x: 2057
    y: 941
Stalingrad:
    x: 2563
    y: 863
Ufa:
    x: 2727
    y: 695
Voronezh:
    x: 2361
    y: 713
Bryansk:
    x: 2199
    y: 765
Belorussia:
    x: 1921
    y: 761
Moscow:
    x: 2277
    y: 605
Penza:
    x: 2467
    y: 527
Leningrad:
    x: 1981
    y: 553
Gorky:
    x: 2401
    y: 389
Perm:
    x: 2653
    y: 395
Vologda:
    x: 2203
    y: 363
Western Siberia:
    x: 3215
    y: 569
Urals:
    x: 2983
    y: 323
Archangel:
    x: 2113
    y: 257
Murmansk:
    x: 1897
    y: 299
Helsinki:
    x: 1739
    y: 421
White Sea:
    x: 2035
    y: 61
Barents Sea:
    x: 1861
    y: 33
Petsamo:
    x: 1725
    y: 183
Narvik:
    x: 1655
    y: 97
Gulf of Bothnia:
    x: 1571
    y: 489
Riga:
    x: 1777
    y: 663
Gallivare:
    x: 1545
    y: 313
Nordkapp Sea:
    x: 1311
    y: 291
Oslo:
    x: 1257
    y: 533
Stockholm:
    x: 1437
    y: 537
Baltic Sea:
    x: 1563
    y: 685
Vilna:
    x: 1771
    y: 869
Konigsberg:
    x: 1633
    y: 829
Warsaw:
    x: 1551
    y: 955
Copenhagen:
    x: 1245
    y: 715
North Sea:
    x: 1033
    y: 795
Ruhr:
    x: 1237
    y: 883
Berlin:
    x: 1367
    y: 965
Lvov:
    x: 1719
    y: 1017
Prague:
    x: 1549
    y: 1105
Budapest:
    x: 1657
    y: 1191
Bucharest:
    x: 1809
    y: 1289
Munich:
    x: 1231
    y: 1125
Vienna:
    x: 1429
    y: 1209
Amsterdam:
    x: 1059
    y: 1011
Lorraine:
    x: 1021
    y: 1193
Glasgow:
    x: 843
    y: 631
London:
    x: 841
    y: 871
Dublin:
    x: 631
    y: 769
Paris:
    x: 853
    y: 1137
Belgrade:
    x: 1669
    y: 1409
Sofia:
    x: 1869
    y: 1423