Austria: [211,169,109]
Italy: [164,162,141]
Latin America: [198,179,139]
USA: [145,186,130]
Ireland: [217,184,143]
Afghanistan: [187,168,128]
Portugal: [234,201,156]
Ocean: [191,227,243]
Persia: [223,191,150]
USSR: [233,138,134]
Czechoslovakia: [196,174,135]
India: [155,202,228]
Norway: [189,170,130]
Spain: [225,205,118]
Hungary: [223,190,149]
Poland: [227,207,121]
Rumania: [206,164,104]
Baltic States: [226,193,152]
Finland: [218,176,116]
Britain: [86,182,222]
Low Countries: [233,174,104]
Middle East: [154,201,227]
Canada: [72,168,208]
Sweden: [216,183,142]
Syria: [187,221,223]
Turkey: [227,206,123]
Germany: [174,174,176]
Libya: [199,197,182]
Albania: [231,199,158]
French North Africa: [181,215,217]
Greece: [214,172,112]
Bulgaria: [224,192,151]
Yugoslavia: [186,167,127]
France: [121,200,205]
Sea: [207,229,240]
Denmark: [185,152,99]