- Fortress:
    rebase: False
    priority: 1
    type: 'G'
    move: 0
    A: 2
    N: 3
    G: 4
    S: 3
- AirForce:
    rebase: True
    priority: 2
    type: 'A'
    move: 2
    A: 3
    N: 1
    G: 1
    S: 1
- Carrier:
    rebase: True
    doubleHit: True
    priority: 3
    type: 'N'
    move: 3
    A: 2
    N: 2
    G: 1
    S: 2
- Submarine:
    rebase: True
    priority: 4
    type: 'S'
    move: 2
    A: 0
    N: 1
    G: 0
    S: 1
- Fleet:
    rebase: True
    priority: 5
    type: 'N'
    move: 3
    A: 1
    N: 3
    G: 1
    S: 2
- Tank:
    rebase: False
    priority: 6
    type: 'G'
    move: 3
    A: 0
    N: 0
    G: 2
    S: 0
- Infantry:
    rebase: False
    priority: 7
    type: 'G'
    move: 2
    A: 1
    N: 1
    G: 3
    S: 0
- Convoy: 
    rebase: False
    priority: 8
    doubleHit: True
    type: 'G'
    move: 2
    A: 0
    N: 0
    G: 0
    S: 0